### PR TITLE
update to 1.5.1 files and hashes

### PR DESCRIPTION
**Pull request by mriagui**

### CODE REVIEW

**Comment by mriagui** [comment]
1.5.1

**Comment by uglymagoo** [comment]
Thanks for your PR, but 1.5.1 is only available for Plex Pass members at the moment and I cannot legally provide the links in my public repo :)

**Comment by mriagui** [comment]
Sorry, didnt realize it was only for Plex Pass members.
I guess i'll have to update it manually then

**Comment by Sojaner** [comment]
How can a Plex Pass member get the link @uglymagoo ? :)

**Comment by uglymagoo** [comment]
You can get the link to my Plex Pass Debian package in the [Plex Pass section of the plex.tv forum.](http://forums.plex.tv/discussion/221444/unofficial-armhf-arm64-multiarch-debian-package-e-g-rpi-2-3-bpi-odroid/p1?new=1). If you are talking about the URLs of the Netgear and Synology packages, just copy the links from https://www.plex.tv/downloads/ .

**Comment by Sojaner** [comment]
Perfect. I found what I needed thanks @uglymagoo :)

**Pull request closed without merging**
