### PR TITLE
To continue the download

### PR DESCRIPTION
**Pull request by jacksonpires**
This option resumes the download if connection fails.

### CODE REVIEW

**Comment by uglymagoo** [comment]
Thanks. I will merge your PR with the next public release.

**Comment by dzuelke** [comment]
This resumes from an existing position if you invoke `curl` *again*, but it won't auto-retry. All `-C` does is instruct `curl` to continue at an offset (and offset `-` takes the file length of `-o`). `curl` usually just exits (and often with code 0 on e.g. 404 failure, unless you specify `--fail`, which I think we want here).

Also, keep in mind that not all servers support resuming at an offset, in which case `curl` would error.

You need at least `--retry` for it to retry under certain scenarios, but that doesn't re-attempt the download for certain disconnects where the connection goes away and the download progress does not match; for that, you need to manually check for exit status 18 and try again:

```
curl_retry_on_18() {
  local ec=18;
  local attempts=0;
  while [[ $ec -eq 18 && $attempts -lt 3 ]]; do
    ((attempts++))
    curl "$@" # -C - would return code 33 if unsupported by server
    ec=$?
  done
  return $ec
}
```

And then use it like `curl_retry_on_18 --fail --progress-bar -o readynas.deb $PMS_URL`, potentially still with `-C -` if the hosts *really* support resuming.

**Comment by jacksonpires** [comment]
Ok, understood! A while ago I had a hard time downloading this file, because the server is really slow. So I unpacked the script and ran with the suggested parameters... that worked back then. But it's up to uglymagoo's decision, after all, it's his script! Thx

**Comment by uglymagoo** [comment]
@jacksonpires Thanks again for your PR but I am afraid I will not merge it. It's a bug in my script that I leave partial and failed downloads in /tmp. I will fix this some time soon, so the parameter you discussed will not have any effect anymore. Moreover, I never got less than 20MB/s from plex.tv during the last 2 years, so I suppose there was a temporary network glitch the last time you tried.

**Pull request closed without merging**
